### ISSUE TITLE
CloudモードでのZooKeeperException

### ISSUE THREAD

**Issue by kakaku-ito-takuya** [sh0nk/solr-sudachi#4]
バージョン：solr 7.7.1

本ライブラリを使わせて頂いております。
SolrCloudモードで本ライブラリのjarを設置して、schema.xmlにsudachiのトークナイザーを
使用するよう定義し
コレクションの作成を試みたところ、以下のエラーログが出力されました。

> Caused by: org.apache.solr.common.cloud.ZooKeeperException: ZkSolrResourceLoader does not support getConfigDir() - likely, what you are trying to do is not supported in ZooKeeper mode
	at org.apache.solr.cloud.ZkSolrResourceLoader.getConfigDir(ZkSolrResourceLoader.java:151)
	at com.github.sh0nk.solr.sudachi.ResourceLoaderHelper.getConfigDir(ResourceLoaderHelper.java:46)
	at com.github.sh0nk.solr.sudachi.SolrSudachiTokenizerFactory.inform(SolrSudachiTokenizerFactory.java:87)
	at org.apache.solr.core.SolrResourceLoader.inform(SolrResourceLoader.java:720)
	at org.apache.solr.schema.IndexSchema.<init>(IndexSchema.java:181)
	at org.apache.solr.schema.IndexSchemaFactory.create(IndexSchemaFactory.java:56)
	at org.apache.solr.schema.IndexSchemaFactory.buildIndexSchema(IndexSchemaFactory.java:75)
	at org.apache.solr.core.ConfigSetService.createIndexSchema(ConfigSetService.java:119)
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:92)

https://github.com/apache/lucene-solr/blob/master/solr/core/src/java/org/apache/solr/cloud/ZkSolrResourceLoader.java#L150
SorCloudではファイルの管理方法が通常とは異なるため、上記部分でそのメソッドは使えないようになっていました。

ご確認のほどよろしくお願いいたします。

**Comment by sh0nk** [comment]
トークナイザの設定はどのようになっていますでしょうか。`README`にあるように、以下の設定を入れた場合、上記の`ResourceLoaderHelper.getConfigDir`が呼ばれないはずですので、一度試してみて頂けますか。

- settingsPath
- systemDictDir

**Comment by kakaku-ito-takuya** [comment]
ご回答ありがとうございます。

```xml
<tokenizer class="com.github.sh0nk.solr.sudachi.SolrSudachiTokenizerFactory" mode="search" settingsPath="solr_sudachi.json" systemDictDir="sudachi"/>
```
上記のようにsettingPathとsystemDictDirの設定を加えて、ZooKeeper側にupconfigした後にコアのリロードを行いました。
（sudachiディレクトリやjsonファイルも併せてupconfigしております）

リロード時に以下のエラーが出力されました。

> Caused by: java.io.IOException: Resource file sudachi does not exist either on /search/solr/kb_shards-1_replica_n1/conf/sudachi or on /search/solr/kb_shards-1_replica_n1/sudachi
	at com.github.sh0nk.solr.sudachi.ResourceLoaderHelper.getResourcePath(ResourceLoaderHelper.java:41)
	at com.github.sh0nk.solr.sudachi.SolrSudachiTokenizerFactory.inform(SolrSudachiTokenizerFactory.java:85)
	at org.apache.solr.core.SolrResourceLoader.inform(SolrResourceLoader.java:720)
	at org.apache.solr.schema.IndexSchema.<init>(IndexSchema.java:181)

getConfigDirは呼ばれずgetResourcePathが呼ばれるようになりました。
SolrCloudの場合、conf配下のファイル等は実ディレクトリ上には展開されず
ZooKeeper側でのみの管理となっているようです。

↓confディレクトリは見当たらず。
```
[kb_shards-1_replica_n1]$ pwd
/search/solr/kb_shards-1_replica_n1
[kb_shards-1_replica_n1]$ ll
合計 4
-rw-rw-r--. 1 solr solr 209  4月  9 14:54 core.properties
drwxrwxr-x. 4 solr solr  42  4月  9 14:54 data
```
getResourcePathは実ディレクトリを参照するため、該当ファイルが見つからず
エラーになったのかと推測しております。

https://github.com/apache/lucene-solr/blob/master/solr/core/src/java/org/apache/solr/cloud/ZkSolrResourceLoader.java#L82
OpenResourceを使わないと駄目なのかなと考えております。

**Comment by sh0nk** [comment]
@kakaku-ito-takuya ご指摘ありがとうございます。仰るように、solrcloud下のconfigファイルに関しては、`ZkSolrResourceLoader#OpenResource`を使うのが正攻法かと思われます。solrcloud対応として別途リリースの必要がありそうです。

一方で、`systemDict`に関してはファイルサイズが数100MBですので、本来メタデータを管理するzookeeperに置くのは良い方法ではないという考えにより、環境によらず、localにファイルを保存するようにしています。

`solr-sudachi`では、辞書ファイルを明示的に与えない場合、指定の`systemDict`のパスにjarファイル内のresourceファイルをコピーする仕組みになっているので、`systemDict`に存在する各shardの絶対ディレクトリを指定してやると、その場所にjarから抽出されたdictファイルが展開され、正常に動作するのではないかと期待されます。
当面のワークアラウンドとしては以下のようになります。（手元にすぐにテストできる環境がないので未テストです。）

- `systemDictDir`: 辞書を展開したいディレクトリを絶対パスで指定
- `settingsPath`: 同様に絶対パスで指定し、該当のパスにファイルを置く

**Comment by kakaku-ito-takuya** [comment]
教えていただきました回避策によって無事ライブラリを読み込むことが出来ました！
analysis画面で形態素解析が出来るとこまで確認済みです。

schema.xml
```xml
<tokenizer class="com.github.sh0nk.solr.sudachi.SolrSudachiTokenizerFactory" mode="search" settingsPath="${solr.solr.home}/${solr.core.name}/solr_sudachi.json" systemDictDir="${solr.solr.home}/${solr.core.name}/sudachi"/>
```
上記のように各shard内に辞書ファイルが展開されるようにしました。
また、shard内ではなく、shardと同階層を指定する形でも問題無く機能しました。

ご丁寧にご対応頂きまして本当にありがとうございます！

**Comment by sh0nk** [comment]
@kakaku-ito-takuya 無事に動作したとのこと、良かったです。solrcloudでの動作についてもREADMEに書き加えますね。
ご報告ありがとうございました。
